
MACHINE ??= "qemuarm64"
DISTRO ?= "poky"
EXTRA_IMAGE_FEATURES ?= "debug-tweaks"
USER_CLASSES ?= "buildstats"
PATCHRESOLVE = "noop"
BB_DISKMON_DIRS ??= "\
    STOPTASKS,${TMPDIR},1G,100K \
    STOPTASKS,${DL_DIR},1G,100K \
    STOPTASKS,${SSTATE_DIR},1G,100K \
    STOPTASKS,/tmp,100M,100K \
    HALT,${TMPDIR},100M,1K \
    HALT,${DL_DIR},100M,1K \
    HALT,${SSTATE_DIR},100M,1K \
    HALT,/tmp,10M,1K"
PACKAGECONFIG:append:pn-qemu-system-native = " sdl"
CONF_VERSION = "2"


# 1. Tăng dung lượng lên 2GB vì HĐH có giao diện đồ hoạ sẽ khá nặng
IMAGE_ROOTFS_EXTRA_SPACE = "2097152"

# 2. Thêm các driver card màn hình ảo (xserver, fbdev) cho QEMU 
IMAGE_INSTALL:append = " gtk+3 openssl openssl-bin libegl mesa libxxf86vm mesa-megadriver xserver-xorg xf86-video-fbdev"

IMAGE_FEATURES += "dev-pkgs"

# 3. Kích hoạt thêm wayland (Yocto phiên bản mới thường dùng song song X11 và Wayland)
DISTRO_FEATURES:append = " opengl x11 wayland" 

TOOLCHAIN_TARGET_TASK:append = " libgl-mesa-dev gtk+3-dev"

IMAGE_FEATURES += "ssh-server-openssh"